/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */

export type InitializeRoleRequestRole =
  (typeof InitializeRoleRequestRole)[keyof typeof InitializeRoleRequestRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InitializeRoleRequestRole = {
  TRAINER: "TRAINER",
  TRAINEE: "TRAINEE",
  PARENT: "PARENT",
  ADMIN: "ADMIN",
} as const;
