/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */

export type OnboardingResponseActiveRole =
  (typeof OnboardingResponseActiveRole)[keyof typeof OnboardingResponseActiveRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OnboardingResponseActiveRole = {
  TRAINER: "TRAINER",
  TRAINEE: "TRAINEE",
  PARENT: "PARENT",
  ADMIN: "ADMIN",
} as const;
