/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type TrainerProfile = {
  gyms?: string[];
  groups?: string[];
  trainings?: string[];
  isOnboardingCompleted?: boolean;
  subscriptions?: string[];
} | null;
