/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */

export interface TrainerProfile {
  gyms?: string[];
  groups?: string[];
  trainings?: string[];
  isOnboardingCompleted?: boolean;
  subscriptions?: string[];
}
