/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateLanguageRequestPreferredLang } from "./updateLanguageRequestPreferredLang";

export interface UpdateLanguageRequest {
  preferredLang: UpdateLanguageRequestPreferredLang;
}
