/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateLanguageRequestPreferredLang =
  (typeof UpdateLanguageRequestPreferredLang)[keyof typeof UpdateLanguageRequestPreferredLang];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateLanguageRequestPreferredLang = {
  en: "en",
  ua: "ua",
  pl: "pl",
} as const;
