/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponsePreferredLang } from "./userResponsePreferredLang";
import type { UserResponseActiveRole } from "./userResponseActiveRole";
import type { UserResponseRolesItem } from "./userResponseRolesItem";
import type { TrainerProfile } from "./trainerProfile";
import type { TraineeProfile } from "./traineeProfile";
import type { ParentProfile } from "./parentProfile";

export interface UserResponse {
  id: string;
  email: string;
  name: string;
  preferredLang: UserResponsePreferredLang;
  activeRole: UserResponseActiveRole;
  roles: UserResponseRolesItem[];
  trainerStepsLeft: string[];
  traineeStepsLeft: string[];
  parentStepsLeft: string[];
  trainerProfile: TrainerProfile;
  traineeProfile: TraineeProfile;
  parentProfile: ParentProfile;
}
