/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */

export type UserResponseRolesItem =
  (typeof UserResponseRolesItem)[keyof typeof UserResponseRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseRolesItem = {
  TRAINER: "TRAINER",
  TRAINEE: "TRAINEE",
  PARENT: "PARENT",
  ADMIN: "ADMIN",
} as const;
