/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponsePreferredLang } from "./userResponsePreferredLang";
import type { UserResponseActiveRole } from "./userResponseActiveRole";
import type { UserResponseRolesItem } from "./userResponseRolesItem";

export interface UserResponse {
  id: string;
  email: string;
  name: string;
  preferredLang: UserResponsePreferredLang;
  activeRole: UserResponseActiveRole;
  roles: UserResponseRolesItem[];
}
