/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Roles API
 * OpenAPI spec version: 1.0.0
 */

export type UserResponseTrainerOnboardingLeftItem =
  (typeof UserResponseTrainerOnboardingLeftItem)[keyof typeof UserResponseTrainerOnboardingLeftItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseTrainerOnboardingLeftItem = {
  gymCreation: "gymCreation",
  groupCreation: "groupCreation",
  subscriptionCreation: "subscriptionCreation",
  trainingCreation: "trainingCreation",
  contactInformationCreation: "contactInformationCreation",
  traineeCreation: "traineeCreation",
} as const;
