/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Authentication API
 * OpenAPI spec version: 1.0.0
 */

export interface AuthResponse {
  accessToken: string;
  /** Whether the user is logging in for the first time */
  isFirstLogin?: boolean;
}
