/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Authentication API
 * OpenAPI spec version: 1.0.0
 */
import type { EmailNotConfirmedResponseError } from "./emailNotConfirmedResponseError";

export type EmailNotConfirmedResponse = {
  message?: string;
  error?: EmailNotConfirmedResponseError;
};
