/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */

export type AttachToTrainingResponseStatus =
  (typeof AttachToTrainingResponseStatus)[keyof typeof AttachToTrainingResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttachToTrainingResponseStatus = {
  added_to_existing_training: "added_to_existing_training",
} as const;
