/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */

export type CreateTrainingResponseStatus =
  (typeof CreateTrainingResponseStatus)[keyof typeof CreateTrainingResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateTrainingResponseStatus = {
  trainingCreated: "trainingCreated",
} as const;
