/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTrainingResponseStatus } from "./createTrainingResponseStatus";

export interface CreateTrainingResponse {
  status: CreateTrainingResponseStatus;
  trainingId: string;
  traineeAdded: boolean;
}
