/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of the subscription
 */
export type CreateSubscriptionsSubscriptionsItemType =
  (typeof CreateSubscriptionsSubscriptionsItemType)[keyof typeof CreateSubscriptionsSubscriptionsItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSubscriptionsSubscriptionsItemType = {
  PERIOD: "PERIOD",
  DAYS: "DAYS",
  PERIOD_AND_DAYS: "PERIOD_AND_DAYS",
} as const;
