/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTrainerProfileRequest {
  specialization?: string;
  experience?: number;
  description?: string;
  achievements?: string[];
}
