/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */

export type CreateGroupsDtoGroupsItem = {
  name: string;
  gymId?: string;
  trainerIds?: string[];
  traineeIds?: string[];
};
