/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */

export type ScanTraineeResponseStatus =
  (typeof ScanTraineeResponseStatus)[keyof typeof ScanTraineeResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScanTraineeResponseStatus = {
  noActiveTraining: "noActiveTraining",
  traineeAlreadyRecorded: "traineeAlreadyRecorded",
  traineeRecordedSuccessfully: "traineeRecordedSuccessfully",
  specifyTraining: "specifyTraining",
} as const;
