/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */
import type { ScanAndCreateRequestTrainingType } from "./scanAndCreateRequestTrainingType";

export type ScanAndCreateRequestTraining = {
  type?: ScanAndCreateRequestTrainingType;
  date?: string;
  durationMin?: number;
  gymId?: string;
  groupId?: string;
  templateId?: string;
};
