/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */
import type { ScanTraineeResponseStatus } from "./scanTraineeResponseStatus";
import type { ScanTraineeResponseTrainingsItem } from "./scanTraineeResponseTrainingsItem";

export interface ScanTraineeResponse {
  status: ScanTraineeResponseStatus;
  trainings?: ScanTraineeResponseTrainingsItem[];
}
