/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */
import type { ScanAndCreateRequestTraining } from "./scanAndCreateRequestTraining";

export interface ScanAndCreateRequest {
  traineeUsername: string;
  training?: ScanAndCreateRequestTraining;
}
