/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */

export type ScanAndCreateRequestTrainingType =
  (typeof ScanAndCreateRequestTrainingType)[keyof typeof ScanAndCreateRequestTrainingType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScanAndCreateRequestTrainingType = {
  INDIVIDUAL: "INDIVIDUAL",
  GROUP: "GROUP",
} as const;
