/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */
import type { TrainingDtoType } from "./trainingDtoType";
import type { TrainingDtoTimeSlotsItem } from "./trainingDtoTimeSlotsItem";

export interface TrainingDto {
  /** Name of the training */
  name: string;
  /** Type of the training */
  type?: TrainingDtoType;
  /** Start date and time of the training */
  startDate?: string;
  /** Duration of the training in minutes */
  durationMin?: number;
  /** ID of the gym where training takes place */
  gymId?: string;
  /** ID of the group for group training */
  groupId?: string;
  /** ID of the training template */
  templateId?: string;
  /** Price of the training */
  price?: number;
  /** Array of trainer IDs for the training */
  trainerIds?: string[];
  /** Flag to indicate if the training should be saved as a template */
  isSaveAsTemplate?: boolean;
  /** Recurring time slots for the training */
  timeSlots?: TrainingDtoTimeSlotsItem[];
}
