/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */

export type TrainingDtoTimeSlotsItem = {
  /** Day of the week (e.g., Monday, Tuesday) */
  dayOfTheWeek: string;
  /** Hour in 24h format */
  hours: number;
  /** Minutes past the hour */
  minutes: number;
};
