/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Trainer API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of the training
 */
export type TrainingDtoType =
  (typeof TrainingDtoType)[keyof typeof TrainingDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TrainingDtoType = {
  INDIVIDUAL: "INDIVIDUAL",
  GROUP: "GROUP",
} as const;
