/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Authentication API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthResponse } from "./authResponse";

/**
 * Authentication successful
 */
export type AuthResponseResponse = AuthResponse;
