/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Authentication API
 * OpenAPI spec version: 1.0.0
 */

export interface ConfirmEmailResponse {
  message: string;
  accessToken: string;
}
