/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Authentication API
 * OpenAPI spec version: 1.0.0
 */

export type EmailNotConfirmedResponseError =
  (typeof EmailNotConfirmedResponseError)[keyof typeof EmailNotConfirmedResponseError];

export const EmailNotConfirmedResponseError = {
  EMAIL_NOT_CONFIRMED: "EMAIL_NOT_CONFIRMED",
} as const;
