/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Authentication API
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterResponse } from "./registerResponse";

/**
 * Registration successful
 */
export type RegisterResponseResponse = RegisterResponse;
