/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Authentication API
 * OpenAPI spec version: 1.0.0
 */
import type { UserActiveRole } from "./userActiveRole";

export interface User {
  id: string;
  email: string;
  name: string;
  activeRole: UserActiveRole;
  isEmailConfirmed: boolean;
}
