/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Authentication API
 * OpenAPI spec version: 1.0.0
 */

export type UserActiveRole =
  (typeof UserActiveRole)[keyof typeof UserActiveRole];

 
export const UserActiveRole = {
  TRAINER: "TRAINER",
  TRAINEE: "TRAINEE",
  PARENT: "PARENT",
  ADMIN: "ADMIN",
  SUPERADMIN: "SUPERADMIN",
} as const;
